### ISSUE TITLE
some bosses attack patterns are now hidden ( patch 106.2)

### ISSUE THREAD

**Issue by lidel97** [seraphinush-gaming/fps-utils-lite#2]
some bosses attacks like fireballs of the 2nd boss in guardian mission "escape from balder's refuge",  vertical and horizontal puddle spit by the 2nd boss "shadows of the gutrends" and the first boss in "ruinos manor", some attacks of the boss in "corrupted skynest" like the long "ice line left to the ground" are now hided if i select the option "fps mode 1" while in the previous versions of this module, anything worked well and i could see them. 
if i try to set "fps mode 0" , all attacks are correctly visualized so it's obvious there are some issues with this patch. i also tried to wipe out, downloaded and reinstalled this module, still won't work.

**Comment by notseraphh** [comment]
Will check thank you

**Comment by notseraphh** [comment]
Fixed https://github.com/seraphinush-gaming/fps-utils-lite/commit/fb4a1162fce8ff0ba946448cb53bc17389fffaa0
